backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "conteudo" # Nome geral da coleção
    label: "Conteúdos do Site"
    files: # A propriedade 'files' que estava faltando
      - name: "posts" # Um identificador para o nosso conjunto de posts
        label: "Posts (Fique por Dentro)"
        file: "_data/posts.json" # O arquivo que será editado
        fields:
          - name: "lista_de_posts"
            label: "Posts"
            widget: list
            fields:
              - {label: "Título", name: "title", widget: "string"}
              - {label: "Data de Publicação", name: "date", widget: "datetime"}
              - {label: "Imagem de Destaque", name: "thumbnail", widget: "image"}
              - {label: "Resumo (para a página inicial)", name: "excerpt", widget: "text"}
              - {label: "Conteúdo Completo do Post", name: "body", widget: "markdown", required: false}
