backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "posts" # Nome da coleção
    label: "Posts (Fique por Dentro)" # Como aparece no menu
    label_singular: "Post" # Rótulo para um item
    folder: "_posts" # Salvará cada post como um arquivo separado nesta pasta
    create: true # ESSENCIAL: Habilita o botão "New Post"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # Campos para cada post
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Data de Publicação", name: "date", widget: "datetime"}
      - {label: "Imagem de Destaque", name: "thumbnail", widget: "image"}
      - {label: "Resumo (para a página inicial)", name: "excerpt", widget: "text"}
      - {label: "Conteúdo Completo do Post", name: "body", widget: "markdown"}
