backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "posts"
    label: "Posts (Fique por Dentro)"
    label_singular: "Post"
    file: "_data/posts.json"
    create: false # Desativado para usar a edição de lista abaixo
    
    # Esta é a estrutura correta para editar uma lista de itens em um arquivo
    fields:
      - name: items
        label: Lista de Posts
        widget: list
        fields:
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Data de Publicação", name: "date", widget: "datetime"}
          - {label: "Imagem de Destaque", name: "thumbnail", widget: "image"}
          - {label: "Resumo (para a página inicial)", name: "excerpt", widget: "text"}
          - {label: "Conteúdo Completo do Post (ainda não usado)", name: "body", widget: "markdown", required: false}
